##Step 2: Data Collection

###Import Necessary Libraries

In [ ]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings('ignore')

###Load Dataset

In [ ]:
online_retail_data = pd.read_excel('Online Retail.xlsx')
online_retail_data

       InvoiceNo StockCode  ... CustomerID         Country
0         536365    85123A  ...    17850.0  United Kingdom
1         536365     71053  ...    17850.0  United Kingdom
2         536365    84406B  ...    17850.0  United Kingdom
3         536365    84029G  ...    17850.0  United Kingdom
4         536365    84029E  ...    17850.0  United Kingdom
...          ...       ...  ...        ...             ...
541904    581587     22613  ...    12680.0          France
541905    581587     22899  ...    12680.0          France
541906    581587     23254  ...    12680.0          France
541907    581587     23255  ...    12680.0          France
541908    581587     22138  ...    12680.0          France

[541909 rows x 8 columns]

##Step 3: Data Understanding

###Perform Initial Investigation

In [ ]:
online_retail_data.shape

(541909, 8)

In [ ]:
online_retail_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
online_retail_data.describe(include='all')

        InvoiceNo StockCode  ...     CustomerID         Country
count    541909.0    541909  ...  406829.000000          541909
unique    25900.0      4070  ...            NaN              38
top      573585.0    85123A  ...            NaN  United Kingdom
freq       1114.0      2313  ...            NaN          495478
mean          NaN       NaN  ...   15287.690570             NaN
min           NaN       NaN  ...   12346.000000             NaN
25%           NaN       NaN  ...   13953.000000             NaN
50%           NaN       NaN  ...   15152.000000             NaN
75%           NaN       NaN  ...   16791.000000             NaN
max           NaN       NaN  ...   18287.000000             NaN
std           NaN       NaN  ...    1713.600303             NaN

[11 rows x 8 columns]

In [ ]:
online_retail_data['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [ ]:
online_retail_data['Country'].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [ ]:
online_retail_data.groupby('Country')['InvoiceNo'].nunique()

Country
Australia                  69
Austria                    19
Bahrain                     4
Belgium                   119
Brazil                      1
Canada                      6
Channel Islands            33
Cyprus                     20
Czech Republic              5
Denmark                    21
EIRE                      360
European Community          5
Finland                    48
France                    461
Germany                   603
Greece                      6
Hong Kong                  15
Iceland                     7
Israel                      9
Italy                      55
Japan                      28
Lebanon                     1
Lithuania                   4
Malta                      10
Netherlands               101
Norway                     40
Poland                     24
Portugal                   71
RSA                         1
Saudi Arabia                2
Singapore                  10
Spain                     105
Sweden                     46
Switzerland                74
USA                         7
United Arab Emirates        3
United Kingdom          23494
Unspecified                13
Name: InvoiceNo, dtype: int64

####As Association of products varies among the countries, i would perform operations for 1 specific country for understanding

In [ ]:
fn_data = online_retail_data[online_retail_data['Country'] == 'France']
fn_data

       InvoiceNo StockCode  ... CustomerID  Country
26        536370     22728  ...    12583.0   France
27        536370     22727  ...    12583.0   France
28        536370     22726  ...    12583.0   France
29        536370     21724  ...    12583.0   France
30        536370     21883  ...    12583.0   France
...          ...       ...  ...        ...      ...
541904    581587     22613  ...    12680.0   France
541905    581587     22899  ...    12680.0   France
541906    581587     23254  ...    12680.0   France
541907    581587     23255  ...    12680.0   France
541908    581587     22138  ...    12680.0   France

[8557 rows x 8 columns]

In [ ]:
fn_data.isna().sum()

InvoiceNo       0
StockCode       0
Description     0
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     66
Country         0
dtype: int64

In [ ]:
del fn_data['CustomerID']

In [ ]:
sa_data = online_retail_data[online_retail_data['Country'] == 'Saudi Arabia']
sa_pivotted_data = pd.pivot_table(data=sa_data,values='Quantity',index='InvoiceNo',columns='Description',aggfunc='sum').fillna(0)
sa_pivotted_data

Description  ASSORTED BOTTLE TOP  MAGNETS   ...  PLASTERS IN TIN STRONGMAN
InvoiceNo                                   ...
544838                                12.0  ...                       12.0
C545507                                0.0  ...                        0.0

[2 rows x 9 columns]

####Implementation of Pivot Table

In [ ]:
fr_pivotted_data = pd.pivot_table(data=fn_data,values='Quantity',index='InvoiceNo',columns='Description',aggfunc='sum').fillna(0)
fr_pivotted_data

Description   50'S CHRISTMAS GIFT BAG LARGE  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                                    ...
536370                                  0.0  ...                              0.0
536852                                  0.0  ...                              0.0
536974                                  0.0  ...                              0.0
537065                                  0.0  ...                              0.0
537463                                  0.0  ...                              0.0
...                                     ...  ...                              ...
C579532                                 0.0  ...                              0.0
C579562                                 0.0  ...                              0.0
C580161                                 0.0  ...                              0.0
C580263                                 0.0  ...                              0.0
C581316                                 0.0  ...                              0.0

[461 rows x 1565 columns]

In [ ]:
fr_pivotted_one_hot = fr_pivotted_data.applymap(lambda x: 0 if x == 0 else 1)

fr_pivotted_one_hot

Description   50'S CHRISTMAS GIFT BAG LARGE  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                                    ...
536370                                    0  ...                                0
536852                                    0  ...                                0
536974                                    0  ...                                0
537065                                    0  ...                                0
537463                                    0  ...                                0
...                                     ...  ...                              ...
C579532                                   0  ...                                0
C579562                                   0  ...                                0
C580161                                   0  ...                                0
C580263                                   0  ...                                0
C581316                                   0  ...                                0

[461 rows x 1565 columns]

###Step 4: Data Mining

In [ ]:
frequent_itemsets = apriori(fr_pivotted_one_hot,min_support=0.02,use_colnames= True)
frequent_itemsets

       support                                           itemsets
0     0.034707                          ( SPACEBOY BABY GIFT SET)
1     0.026030                           (10 COLOUR SPACEBOY PEN)
2     0.021692               (12 PENCILS TALL TUBE RED RETROSPOT)
3     0.030369               (3 PIECE SPACEBOY COOKIE CUTTER SET)
4     0.041215                    (36 PENCILS TUBE RED RETROSPOT)
...        ...                                                ...
1311  0.023861  (PACK OF 6 SKULL PAPER CUPS, SET/6 RED SPOTTY ...
1312  0.021692  (PACK OF 6 SKULL PAPER CUPS, SET/6 RED SPOTTY ...
1313  0.023861  (SET/6 RED SPOTTY PAPER CUPS, PACK OF 6 SKULL ...
1314  0.023861  (PACK OF 6 SKULL PAPER CUPS, SET/6 RED SPOTTY ...
1315  0.021692  (PACK OF 6 SKULL PAPER CUPS, SET/6 RED SPOTTY ...

[1316 rows x 2 columns]

In [ ]:
fr_best_association = association_rules(frequent_itemsets,metric='confidence',min_threshold=0.02)
fr_best_association.head(20)

                             antecedents  ... kulczynski
0               (10 COLOUR SPACEBOY PEN)  ...   0.519293
1                              (POSTAGE)  ...   0.519293
2   (3 PIECE SPACEBOY COOKIE CUTTER SET)  ...   0.485186
3                              (POSTAGE)  ...   0.485186
4        (36 PENCILS TUBE RED RETROSPOT)  ...   0.279235
5                              (POSTAGE)  ...   0.279235
6          (4 TRADITIONAL SPINNING TOPS)  ...   0.330575
7              (MINI PAINT SET VINTAGE )  ...   0.330575
8          (4 TRADITIONAL SPINNING TOPS)  ...   0.428227
9                              (POSTAGE)  ...   0.428227
10      (ALARM CLOCK BAKELIKE CHOCOLATE)  ...   0.517685
11                             (POSTAGE)  ...   0.517685
12          (ALARM CLOCK BAKELIKE GREEN)  ...   0.544872
13          (ALARM CLOCK BAKELIKE IVORY)  ...   0.544872
14          (ALARM CLOCK BAKELIKE GREEN)  ...   0.549020
15         (ALARM CLOCK BAKELIKE ORANGE)  ...   0.549020
16          (ALARM CLOCK BAKELIKE GREEN)  ...   0.734295
17           (ALARM CLOCK BAKELIKE PINK)  ...   0.734295
18          (ALARM CLOCK BAKELIKE GREEN)  ...   0.816355
19           (ALARM CLOCK BAKELIKE RED )  ...   0.816355

[20 rows x 14 columns]

In [ ]:
fr_best_association.to_csv('fr_best_anticedents_consequents.csv')