##Step 2: Data Collection

###Import Necessary Libraries

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import pairwise_distances

###Load Dataset

In [ ]:
movie_data = pd.read_csv('Movie.csv')
movie_data

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

##Step 3:Data Understanding

###Perform Initial Investigation

In [ ]:
movie_data.shape

(8992, 3)

In [ ]:
movie_data.isna().sum()

userId    0
movie     0
rating    0
dtype: int64

In [ ]:
movie_data.describe(include='all')

             userId             movie       rating
count   8992.000000              8992  8992.000000
unique          NaN                10          NaN
top             NaN  Toy Story (1995)          NaN
freq            NaN              2569          NaN
mean    3521.880116               NaN     3.557162
std     2012.497384               NaN     0.967071
min        1.000000               NaN     0.500000
25%     1779.000000               NaN     3.000000
50%     3530.000000               NaN     3.500000
75%     5213.250000               NaN     4.000000
max     7120.000000               NaN     5.000000

In [ ]:
movie_data['userId'].nunique()

4081

In [ ]:
movie_data['movie'].nunique()

10

In [ ]:
movie_data['movie'].unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

##To understand the users movie similarity we build correlation.

In [ ]:
pvt_table = pd.pivot_table(data=movie_data,values='rating',index='movie',columns='userId',aggfunc='sum').fillna(0)
pvt_table.index = movie_data['movie'].unique()
pvt_table.columns = movie_data['userId'].unique()
pvt_table

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
Toy Story (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
Jumanji (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Waiting to Exhale (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Father of the Bride Part II (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0
Heat (1995),0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
Sabrina (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Tom and Huck (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sudden Death (1995),0.0,0.0,4.0,0.0,0.0,5.0,0.0,4.0,4.0,4.5,...,0.0,4.0,0.0,4.0,0.0,0.0,4.0,4.0,5.0,4.5
GoldenEye (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
pvt_table.corr().round(3).head(20)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.000,-0.111,-0.111,-0.165,1.000,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,1.000,0.667,-0.167,-0.111,-0.166,-0.351,-0.111,0.479
6,-0.111,1.000,-0.111,-0.165,-0.111,0.276,0.667,0.564,-0.111,-0.159,...,-0.111,-0.111,-0.111,-0.167,-0.167,-0.111,-0.166,0.351,-0.111,-0.218
8,-0.111,-0.111,1.000,-0.165,-0.111,0.601,-0.167,0.398,1.000,0.862,...,-0.111,1.000,-0.111,0.667,-0.167,-0.111,0.720,0.351,1.000,0.566
10,-0.165,-0.165,-0.165,1.000,-0.165,-0.313,-0.247,0.484,-0.165,0.245,...,0.776,-0.165,-0.165,-0.247,0.987,-0.165,-0.246,0.483,-0.165,-0.322
11,1.000,-0.111,-0.111,-0.165,1.000,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,1.000,0.667,-0.167,-0.111,-0.166,-0.351,-0.111,0.479
12,-0.211,0.276,0.601,-0.313,-0.211,1.000,0.658,0.344,0.601,0.444,...,-0.211,0.601,-0.211,0.292,-0.317,-0.211,0.332,0.539,0.601,0.668
13,-0.167,0.667,-0.167,-0.247,-0.167,0.658,1.000,0.224,-0.167,-0.238,...,-0.167,-0.167,-0.167,-0.250,-0.250,-0.167,-0.249,0.395,-0.167,0.196
14,-0.265,0.564,0.398,0.484,-0.265,0.344,0.224,1.000,0.398,0.569,...,0.398,0.398,-0.265,0.100,0.473,-0.265,0.132,0.813,0.398,-0.052
16,-0.111,-0.111,1.000,-0.165,-0.111,0.601,-0.167,0.398,1.000,0.862,...,-0.111,1.000,-0.111,0.667,-0.167,-0.111,0.720,0.351,1.000,0.566
19,-0.159,-0.159,0.862,0.245,-0.159,0.444,-0.238,0.569,0.862,1.000,...,0.408,0.862,-0.159,0.527,0.187,-0.159,0.577,0.412,0.862,0.409
22,-0.319,0.319,0.532,-0.068,-0.319,0.763,0.479,0.509,0.532,0.326,...,-0.319,0.532,-0.319,0.160,0.000,0.106,0.499,0.741,0.532,0.376
23,0.430,-0.215,0.645,0.228,0.430,0.220,-0.323,0.385,0.645,0.813,...,0.430,0.645,0.430,0.807,0.161,-0.215,0.365,0.170,0.645,0.590
24,-0.165,-0.165,0.763,-0.244,-0.165,0.893,0.294,0.160,0.763,0.617,...,-0.165,0.763,-0.165,0.449,-0.248,-0.165,0.494,0.408,0.763,0.784
31,-0.111,-0.111,-0.111,0.776,-0.111,-0.211,-0.167,0.398,-0.111,0.408,...,1.000,-0.111,-0.111,-0.167,0.667,-0.111,-0.166,0.176,-0.111,-0.218
34,-0.167,-0.167,0.667,0.282,-0.167,0.292,-0.250,0.473,0.667,0.527,...,-0.167,0.667,-0.167,0.375,0.375,-0.167,0.416,0.659,0.667,0.261
39,-0.111,-0.111,-0.111,0.541,-0.111,-0.211,-0.167,0.232,-0.111,-0.159,...,-0.111,-0.111,-0.111,-0.167,0.667,-0.111,-0.166,0.527,-0.111,-0.218
47,-0.270,0.299,0.441,0.051,-0.270,0.776,0.555,0.522,0.441,0.267,...,-0.270,0.441,-0.270,0.128,0.128,-0.270,0.163,0.855,0.441,0.418
53,-0.111,-0.111,-0.111,0.541,-0.111,-0.211,-0.167,0.232,-0.111,-0.159,...,-0.111,-0.111,-0.111,-0.167,0.667,-0.111,-0.166,0.527,-0.111,-0.218
54,-0.161,-0.161,0.441,0.399,-0.161,0.135,-0.241,0.425,0.441,0.324,...,-0.161,0.441,-0.161,0.211,0.512,-0.161,0.240,0.666,0.441,0.110
58,-0.111,-0.111,1.000,-0.165,-0.111,0.601,-0.167,0.398,1.000,0.862,...,-0.111,1.000,-0.111,0.667,-0.167,-0.111,0.720,0.351,1.000,0.566

In [ ]:
movie_data[(movie_data['userId'] == 8) | (movie_data['userId'] == 16)]

      userId                    movie  rating
2          8         Toy Story (1995)     4.0
8         16         Toy Story (1995)     3.0
3727       8  Grumpier Old Men (1995)     5.0
5205       8              Heat (1995)     3.0
5207      16              Heat (1995)     3.0
7445       8         GoldenEye (1995)     4.0

###Building UBCF Recommendation

####1. Euclidean method

In [ ]:
euclidean_pvt_table = pd.pivot_table(data=movie_data,values='rating',index='userId',columns='movie',aggfunc='sum').fillna(0)
euclidean_pvt_table.index =  movie_data['userId'].unique()
euclidean_pvt_table

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
3,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
10,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7044,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7070,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7080,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7105,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0

In [ ]:
euclidean_correlation = pd.DataFrame(pairwise_distances(X=euclidean_pvt_table,metric='euclidean'))
euclidean_correlation.index = movie_data['userId'].unique()
euclidean_correlation.columns = movie_data['userId'].unique()
euclidean_correlation.head(20)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.000000,5.315073,5.315073,6.103278,0.500000,8.440972,5.500000,8.845903,5.315073,6.224950,...,4.031129,5.315073,1.500000,4.031129,5.500000,5.315073,6.363961,9.394147,6.103278,6.041523
6,5.315073,0.000000,5.656854,6.403124,5.000000,7.141428,3.162278,6.480741,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,5.830952,5.656854,6.652067,7.745967,6.403124,8.261356
8,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,...,4.472136,0.000000,4.472136,4.000000,5.830952,5.656854,3.500000,7.745967,1.000000,5.678908
10,6.103278,6.403124,6.403124,0.000000,5.830952,9.165151,6.557439,6.403124,6.403124,5.612486,...,3.605551,6.403124,5.385165,7.549834,1.000000,6.403124,7.297260,6.855655,7.071068,8.789198
11,0.500000,5.000000,5.000000,5.830952,0.000000,8.246211,5.196152,8.660254,5.000000,5.958188,...,3.605551,5.000000,1.000000,4.123106,5.196152,5.000000,6.103278,9.219544,5.830952,6.103278
12,8.440972,7.141428,5.916080,9.165151,8.246211,0.000000,5.385165,7.416198,5.916080,6.363961,...,7.937254,5.916080,7.937254,7.141428,8.774964,8.660254,6.873864,6.403124,5.830952,5.123475
13,5.500000,3.162278,5.830952,6.557439,5.196152,5.385165,0.000000,7.348469,5.830952,6.670832,...,4.690416,5.830952,4.690416,7.071068,6.000000,5.830952,6.800735,7.211103,6.557439,6.800735
14,8.845903,6.480741,7.071068,6.403124,8.660254,7.416198,7.348469,0.000000,7.071068,6.041523,...,7.348469,7.071068,8.366600,8.124038,6.480741,9.055385,7.889867,4.000000,7.141428,9.069179
16,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,...,4.472136,0.000000,4.472136,4.000000,5.830952,5.656854,3.500000,7.745967,1.000000,5.678908
19,6.224950,6.519202,2.549510,5.612486,5.958188,6.363961,6.670832,6.041523,2.549510,0.000000,...,4.527693,2.549510,5.522681,4.743416,5.431390,6.519202,4.330127,7.176350,2.549510,6.184658
22,7.697402,6.244998,5.567764,7.348469,7.483315,4.242641,5.385165,5.744563,5.567764,6.123724,...,7.141428,5.567764,7.141428,6.855655,6.855655,6.855655,5.408327,4.358899,5.656854,6.264982
23,5.024938,7.071068,4.242641,5.916080,5.000000,7.280110,7.211103,6.633250,4.242641,3.082207,...,5.099020,4.242641,5.099020,3.162278,5.830952,7.071068,5.500000,7.745967,4.358899,5.123475
24,6.689544,6.964194,3.535534,7.582875,6.442049,3.391165,5.431390,7.905694,3.535534,4.301163,...,6.041523,3.535534,6.041523,5.338539,7.106335,6.964194,4.974937,7.176350,3.535534,4.031129
31,4.031129,4.472136,4.472136,3.605551,3.605551,7.937254,4.690416,7.348469,4.472136,4.527693,...,0.000000,4.472136,2.828427,6.000000,3.162278,4.472136,5.678908,8.246211,5.385165,7.500000
34,5.500000,5.830952,3.162278,5.000000,5.196152,6.855655,6.000000,6.480741,3.162278,4.183300,...,4.690416,3.162278,4.690416,5.099020,4.242641,5.830952,4.716991,6.324555,3.605551,6.576473
39,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,3.162278,5.656854,6.652067,7.211103,6.403124,8.261356
47,10.161201,8.660254,8.185353,9.273618,10.000000,5.099020,7.416198,6.855655,8.185353,8.514693,...,9.746794,8.185353,9.746794,9.110434,8.888194,10.344080,8.902247,3.872983,8.124038,7.632169
53,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,3.162278,5.656854,6.652067,7.211103,6.403124,8.261356
54,6.800735,7.071068,5.099020,5.385165,6.557439,7.937254,7.211103,6.782330,5.099020,5.787918,...,6.164414,5.099020,6.164414,6.480741,4.690416,7.071068,6.184658,6.000000,5.385165,7.697402
58,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,...,4.472136,0.000000,4.472136,4.000000,5.830952,5.656854,3.500000,7.745967,1.000000,5.678908

In [ ]:
movie_data[(movie_data['userId'] == 8) | (movie_data['userId'] == 16)]

      userId                    movie  rating
2          8         Toy Story (1995)     4.0
8         16         Toy Story (1995)     3.0
3727       8  Grumpier Old Men (1995)     5.0
5205       8              Heat (1995)     3.0
5207      16              Heat (1995)     3.0
7445       8         GoldenEye (1995)     4.0

####2.Cosine Correlation

In [ ]:
cosine_correlation = pd.DataFrame(1-pairwise_distances(X=euclidean_pvt_table,metric='cosine'))
cosine_correlation.index = movie_data['userId'].unique()
cosine_correlation.columns = movie_data['userId'].unique()
cosine_correlation

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
6,0.000000,1.000000,0.000000,0.000000,0.000000,0.390567,0.707107,0.615457,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.458831,0.000000,0.000000
8,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
10,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.615457,0.000000,0.388514,...,0.800000,0.000000,0.000000,0.000000,0.989949,0.000000,0.000000,0.619422,0.000000,0.000000
11,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.658505,0.000000,0.000000,0.000000
7070,0.000000,0.000000,0.752577,0.000000,0.000000,0.489886,0.000000,0.370543,0.752577,0.657870,...,0.000000,0.752577,0.000000,0.532152,0.000000,0.658505,1.000000,0.345306,0.752577,0.468511
7080,0.000000,0.458831,0.458831,0.619422,0.000000,0.701884,0.567775,0.889532,0.458831,0.568212,...,0.344124,0.458831,0.000000,0.324443,0.648886,0.000000,0.345306,1.000000,0.458831,0.476071
7087,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
7105,0.553372,0.000000,0.622543,0.000000,0.553372,0.765455,0.391293,0.306519,0.622543,0.544201,...,0.000000,0.622543,0.553372,0.831497,0.000000,0.000000,0.468511,0.476071,0.622543,1.000000

###observing the distances to find relationship

In [ ]:
euclidean_correlation.iloc[:20,:20]

,3,6,8,10,11,12,13,14,16,19,22,23,24,31,34,39,47,53,54,58
3,0.000000,5.315073,5.315073,6.103278,0.500000,8.440972,5.500000,8.845903,5.315073,6.224950,7.697402,5.024938,6.689544,4.031129,5.500000,5.315073,10.161201,5.315073,6.800735,5.315073
6,5.315073,0.000000,5.656854,6.403124,5.000000,7.141428,3.162278,6.480741,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,5.830952,5.656854,8.660254,5.656854,7.071068,5.656854
8,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000
10,6.103278,6.403124,6.403124,0.000000,5.830952,9.165151,6.557439,6.403124,6.403124,5.612486,7.348469,5.916080,7.582875,3.605551,5.000000,4.123106,9.273618,4.123106,5.385165,6.403124
11,0.500000,5.000000,5.000000,5.830952,0.000000,8.246211,5.196152,8.660254,5.000000,5.958188,7.483315,5.000000,6.442049,3.605551,5.196152,5.000000,10.000000,5.000000,6.557439,5.000000
12,8.440972,7.141428,5.916080,9.165151,8.246211,0.000000,5.385165,7.416198,5.916080,6.363961,4.242641,7.280110,3.391165,7.937254,6.855655,8.660254,5.099020,8.660254,7.937254,5.916080
13,5.500000,3.162278,5.830952,6.557439,5.196152,5.385165,0.000000,7.348469,5.830952,6.670832,5.385165,7.211103,5.431390,4.690416,6.000000,5.830952,7.416198,5.830952,7.211103,5.830952
14,8.845903,6.480741,7.071068,6.403124,8.660254,7.416198,7.348469,0.000000,7.071068,6.041523,5.744563,6.633250,7.905694,7.348469,6.480741,7.615773,6.855655,7.615773,6.782330,7.071068
16,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000
19,6.224950,6.519202,2.549510,5.612486,5.958188,6.363961,6.670832,6.041523,2.549510,0.000000,6.123724,3.082207,4.301163,4.527693,4.183300,6.519202,8.514693,6.519202,5.787918,2.549510
22,7.697402,6.244998,5.567764,7.348469,7.483315,4.242641,5.385165,5.744563,5.567764,6.123724,0.000000,7.000000,4.743416,7.141428,4.795832,6.244998,3.741657,6.244998,5.196152,5.567764
23,5.024938,7.071068,4.242641,5.916080,5.000000,7.280110,7.211103,6.633250,4.242641,3.082207,7.000000,0.000000,5.522681,5.099020,5.291503,7.071068,9.219544,7.071068,6.633250,4.242641
24,6.689544,6.964194,3.535534,7.582875,6.442049,3.391165,5.431390,7.905694,3.535534,4.301163,4.743416,5.522681,0.000000,6.041523,4.847680,6.964194,6.595453,6.964194,6.284903,3.535534
31,4.031129,4.472136,4.472136,3.605551,3.605551,7.937254,4.690416,7.348469,4.472136,4.527693,7.141428,5.099020,6.041523,0.000000,4.690416,4.472136,9.746794,4.472136,6.164414,4.472136
34,5.500000,5.830952,3.162278,5.000000,5.196152,6.855655,6.000000,6.480741,3.162278,4.183300,4.795832,5.291503,4.847680,4.690416,0.000000,3.162278,7.000000,3.162278,2.000000,3.162278
39,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,3.162278,0.000000,8.185353,0.000000,3.162278,5.656854
47,10.161201,8.660254,8.185353,9.273618,10.000000,5.099020,7.416198,6.855655,8.185353,8.514693,3.741657,9.219544,6.595453,9.746794,7.000000,8.185353,0.000000,8.185353,6.708204,8.185353
53,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,3.162278,0.000000,8.185353,0.000000,3.162278,5.656854
54,6.800735,7.071068,5.099020,5.385165,6.557439,7.937254,7.211103,6.782330,5.099020,5.787918,5.196152,6.633250,6.284903,6.164414,2.000000,3.162278,6.708204,3.162278,0.000000,5.099020
58,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000

In [ ]:
movie_data[(movie_data['userId'] == 39) | (movie_data['userId'] == 53)]

      userId             movie  rating
15        39  Toy Story (1995)     5.0
17        53  Toy Story (1995)     4.0
5214      39       Heat (1995)     5.0

##